name: Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      PG_URL: ${{ secrets.PG_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: |
          set -o pipefail

          # Run drizzle-kit, capture stdout and stderr separately
          npx drizzle-kit push --force >stdout.log 2>stderr.log

          echo "STDOUT:"
          cat stdout.log

          echo "STDERR:"
          cat stderr.log

          # If stderr is not empty, fail
          if [ -s stderr.log ]; then
            echo "❌ drizzle-kit emitted errors to stderr"
            exit 1
          fi
